---

- hosts: all
  become: true
  tasks:
  
  - name: update repository index
    yum:
      update_cache: yes
    when: ansible_distribution in ["CentOS"]

  - name: install git & vim
    package:
      name: 
        - "{{ git_package }}"
        - "{{ vim_package }}"
      state: latest
      update_cache: yes
    when: ansible_distribution == "CentOS" and ansible_product_name == "Alibaba Cloud ECS"
